# https://github.com/google/yamlfmt/blob/main/docs/config-file.md
# https://github.com/google/yamlfmt/blob/main/docs/command-usage.md
continue_on_error: false
doublestar: false
exclude:
  - node_modules
extensions:
  - yaml
  - yml
gitignore_excludes: false
gitignore_path: .gitignore
include: []
line_ending: lf
match_type: standard
output_format: default
regex_exclude: []
formatter:
  array_indent: 0
  disallow_anchors: false
  drop_merge_tag: true
  eof_newline: true
  include_document_start: false
  indent: 2
  indent_root_array: false
  indentless_arrays: false
  line_ending: lf
  max_line_length: 0
  pad_line_comments: 1
  retain_line_breaks: false
  retain_line_breaks_single: true
  scan_folded_as_literal: true
  strip_directives: false
  trim_trailing_whitespace: false
  type: basic
