version: 2.1
setup: true
orbs:
  # orb info: https://circleci.com/developer/orbs/orb/circleci/orb-tools
  # changelog: https://github.com/CircleCI-Public/orb-tools-orb/releases
  orb-tools: circleci/orb-tools@12.1.0
  # orb info: https://circleci.com/developer/orbs/orb/circleci/shellcheck
  # changelog: https://github.com/CircleCI-Public/shellcheck-orb/releases
  shellcheck: circleci/shellcheck@3.2.0

filters: &filters
  tags:
    only: /.*/

jobs:
  lint_and_format:
    executor: rynkowsg/docker_x86_cimg_base
    steps:
      - checkout/checkout: {depth: 1}
      - asdf/install: {version: 0.14.0}
      - restore_cache:
          name: asdf - restore cache (partial)
          keys:
            - asdf-{{ checksum ".tool-versions" }}
      - run:
          name: asdf - add plugin
          command: |
            git config --global advice.detachedHead false
            asdf plugin add babashka https://github.com/fredZen/asdf-babashka.git
            asdf plugin add java https://github.com/halcyon/asdf-java.git
            asdf plugin add shellcheck https://github.com/luizm/asdf-shellcheck.git
            asdf plugin add shfmt https://github.com/luizm/asdf-shfmt.git
      - run:
          name: asdf - install tools
          command: |
            asdf install java
            . ~/.asdf/plugins/java/set-java-home.bash
            asdf install babashka
            asdf install shellcheck
            asdf install shfmt
            bash --version
            bb --version
            java --version
            shellcheck --version
            shfmt --version
      - save_cache:
          name: asdf - save cache (partial)
          key: asdf-{{ checksum ".tool-versions" }}
          paths:
            - ~/.asdf/installs
            - ~/.asdf/plugins
            - ~/.asdf/shims
      - rynkowsg/install_sosh: {version: "v0.2.0"}
      - run: make lint
      - run: make format-check

workflows:
  lint-pack:
    jobs:
      - shellcheck/check:
          filters: *filters

      - orb-tools/lint:
          executor: {name: orb-tools/python, resource_class: small}
          filters: *filters

      - orb-tools/pack:
          executor: {name: orb-tools/default, resource_class: small}
          filters: *filters

      - orb-tools/review:
          executor: {name: orb-tools/default, resource_class: small}
          filters: *filters

      - orb-tools/continue:
          executor: {name: orb-tools/default, resource_class: small}
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck/check
          filters: *filters
          orb_name: rynkowsg
          pipeline_number: <<pipeline.number>>
          vcs_type: <<pipeline.project.type>>
