version: 2.1
setup: true
orbs:
  # orb info: https://circleci.com/developer/orbs/orb/circleci/orb-tools
  # changelog: https://github.com/CircleCI-Public/orb-tools-orb/releases
  orb-tools: circleci/orb-tools@12.1.0
  # orb info: https://circleci.com/developer/orbs/orb/circleci/shellcheck
  # changelog: https://github.com/CircleCI-Public/shellcheck-orb/releases
  shellcheck: circleci/shellcheck@3.2.0

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - shellcheck/check:
          filters: *filters

      - orb-tools/lint:
          executor: {name: orb-tools/python, resource_class: small}
          filters: *filters

      - orb-tools/pack:
          executor: {name: orb-tools/default, resource_class: small}
          filters: *filters

      - orb-tools/review:
          executor: {name: orb-tools/default, resource_class: small}
          filters: *filters

      - orb-tools/continue:
          executor: {name: orb-tools/default, resource_class: small}
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck/check
          filters: *filters
          orb_name: rynkowsg
          pipeline_number: <<pipeline.number>>
          vcs_type: <<pipeline.project.type>>
