version: 2.1

setup: true

orbs:
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/asdf
  asdf: rynkowsg/asdf@0.2.0
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/checkout
  checkout: rynkowsg/checkout@0.3.1
  # orb info: https://circleci.com/developer/orbs/orb/circleci/orb-tools
  # changelog: https://github.com/CircleCI-Public/orb-tools-orb/releases
  orb-tools: circleci/orb-tools@12.3.1
  # orb info: https://circleci.com/developer/orbs/orb/circleci/shellcheck
  # changelog: https://github.com/CircleCI-Public/shellcheck-orb/releases
  shellcheck: circleci/shellcheck@3.4.0

filters: &filters
  tags:
    only: /.*/

jobs:
  lint_and_format:
    executor: rynkowsg/docker_x86_cimg_base
    steps:
      - checkout/checkout: {depth: 1}
      - asdf/install: {version: 0.15.0}
      - asdf/cache_restore
      - run:
          name: asdf - add plugins & tools
          command: |
            # install asdf-plugin-manager at first
            asdf plugin-add asdf-plugin-manager https://github.com/asdf-community/asdf-plugin-manager.git
            asdf install asdf-plugin-manager
            echo
            asdf-plugin-manager add babashka && asdf install babashka
            asdf-plugin-manager add java && asdf install java
            asdf-plugin-manager add shellcheck && asdf install shellcheck
            asdf-plugin-manager add shfmt && asdf install shfmt
            # java specific
            . ~/.asdf/plugins/java/set-java-home.bash
            echo ". ~/.asdf/plugins/java/set-java-home.bash" >> $BASH_ENV
            echo "JAVA_HOME=$(asdf where java)" >> $BASH_ENV
            # review all tools installed
            set -x
            bash --version
            bb --version
            java --version
            shellcheck --version
            shfmt --version
      - asdf/cache_save
      - rynkowsg/install_sosh: {version: "v0.2.0"}
      - run: make lint
      - run: make format-check

workflows:
  lint-pack:
    jobs:
      - shellcheck/check:
          filters: *filters

      - orb-tools/lint:
          executor: {name: orb-tools/python, resource_class: small}
          filters: *filters

      - orb-tools/pack:
          executor: {name: orb-tools/default, resource_class: small}
          filters: *filters

      - orb-tools/review:
          executor: {name: orb-tools/default, resource_class: small}
          filters: *filters

      - orb-tools/continue:
          executor: {name: orb-tools/default, resource_class: small}
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck/check
          filters: *filters
          orb_name: rynkowsg
          pipeline_number: <<pipeline.number>>
          vcs_type: <<pipeline.project.type>>
