description: >
  Use sample executors

usage:
  version: 2.1
  orbs:
    rynkowsg: rynkowsg/rynkowsg@0.1.2

jobs:
  test_on_docker:
    executor: rynkowsg/docker_x86_cimg_base
    steps:
      - run: uname -a
  test_on_machine:
    executor: rynkowsg/machine_x86_ubuntu2204
    steps:
      - run: uname -a

  workflows:
    test:
      jobs:
        - test_on_docker
        - test_on_machine
